version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
      - "25500-25600:25500-255600"
    volumes: 
      - ./docker/minecraft_servers:/minecraft_servers
      - ./docker/db:/crafty_db
